<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <PlatformTarget>x64</PlatformTarget>
    <UseWindowsForms>true</UseWindowsForms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DebugType>embedded</DebugType>
    <PathMap>$(MSBuildProjectDirectory)=$(MSBuildProjectName)</PathMap>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="ExileCore">
      <HintPath>$(exileCore2Package)\ExileCore2.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="GameOffsets">
      <HintPath>$(exileCore2Package)\GameOffsets2.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
</Project>
